name: "Terraform"

on:
  push:
    branches: ["master"]
  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
      - name: AWS config SSO
        run: |
          mkdir -p ~/.aws
          echo "[profile fiap-env]
          sso_start_url = ${{ secrets.SSO_START_URL }}
          sso_region = sa-east-1
          sso_account_id = ${{ secrets.ACCOUNT_ID }}
          sso_role_name = ${{ secrets.SSO_ROLE_NAME }}
          region = sa-east-1
          output = json" > ~/.aws/config

      - name: AWS login SSO
        run: |
          aws sso login --profile fiap-env
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Plan
        run: terraform plan -input=false -var="rds_password=${{ secrets.TF_VAR_RDS_PASSWORD }}" -var="ecs_namespace=${{ secrets.TF_VAR_ECS_NAMESPACE }}" -var="rds_host=${{ secrets.TF_VAR_RDS_HOST }}"

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false -var="rds_password=${{ secrets.TF_VAR_RDS_PASSWORD }}" -var="ecs_namespace=${{ secrets.TF_VAR_ECS_NAMESPACE }}" -var="rds_host=${{ secrets.TF_VAR_RDS_HOST }}"
